theme: jekyll-theme-minimal
title: Glimma
url: "https://ztripez.github.io"
baseurl: "/glimma"
exclude:
  - vendor/

# Custom navigation
navigation:
  - title: Home
    url: /
  - title: Playground
    url: /playground.html
  - title: Examples
    url: /examples.html
  - title: Specification
    url: /spec.md
