# .github/workflows/docs-pages.yml
name: Deploy Jekyll docs site to GitHub Pages

on:
  # Builds only on a new published release (or when run manually)
  # release:
  #   types: [published]
  workflow_dispatch:

# GitHub Pages permissions
permissions:
  contents: read
  pages: write
  id-token: write

# One deployment at a time; let in-flight runs finish
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs          # your docs folder
          destination: ./_site    # build output

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site           # same as destination above

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
